---
name: push

on:
  push:
    branches:
      - main

jobs:
  test-unit:
    name: test-unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: test-unit
        run: |
          make test-unit